name = "PlotCurveTopologyForBivariatePolynomial"
uuid = "4098c26b-f9df-4451-8f27-5d8a9793f9f5"
authors = ["Dai Yuejia"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
